const STORAGE='nicopanel-beta-v01';
const pad=n=>String(n).padStart(2,'0');
const iso=(y,m,d)=>`${y}-${pad(m)}-${pad(d)}`;
const fmt=d=>new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(d+'T12:00:00'));
const initials=n=>n.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();
const today=new Date();

const seed={
 people:[
  {id:'p1',name:'Anna Schneider',caseNumber:'NP-2026-101',category:'Rechtliche Betreuung',notes:[{id:'n1',text:'Rücksprache mit Betreuungsgericht nach Eingang der Unterlagen.',created:'2026-08-21'}]},
  {id:'p2',name:'Mehmet Kaya',caseNumber:'NP-2026-102',category:'Sozialbetreuung',notes:[{id:'n2',text:'Wohnungsangelegenheit hat aktuell Priorität.',created:'2026-08-22'}]},
  {id:'p3',name:'Lena Hoffmann',caseNumber:'NP-2026-103',category:'Behördenangelegenheit',notes:[]}
 ],
 mails:[
  {id:'m1',from:'Betreuungsgericht Koblenz',sender:'poststelle@gericht.example',subject:'Unterlagen im Verfahren Anna Schneider',date:'2026-08-25',unread:true,personId:'p1',body:'Sehr geehrte Damen und Herren,\n\nfür das laufende Verfahren Anna Schneider benötigen wir die ergänzende Stellungnahme bis zum 02.09.2026. Bitte reichen Sie die Unterlagen fristgerecht ein.\n\nMit freundlichen Grüßen\nBetreuungsgericht Koblenz'},
  {id:'m2',from:'Sozialamt',sender:'fallmanagement@sozialamt.example',subject:'Nachweise zu Mehmet Kaya',date:'2026-08-25',unread:true,personId:null,body:'Guten Tag,\n\nzu Herrn Mehmet Kaya fehlen noch die aktuellen Kontoauszüge. Bitte übersenden Sie diese spätestens bis 28.08.2026.\n\nVielen Dank.'},
  {id:'m3',from:'Wohnungsverwaltung Rhein',sender:'service@wohnraum.example',subject:'Termin Wohnungsbesichtigung',date:'2026-08-24',unread:false,personId:'p2',body:'Für Mehmet Kaya können wir einen Termin am 31.08.2026 um 10:30 Uhr anbieten. Bitte bestätigen Sie kurz.'},
  {id:'m4',from:'Krankenkasse',sender:'service@krankenkasse.example',subject:'Rückmeldung benötigt – Lena Hoffmann',date:'2026-08-23',unread:true,personId:null,body:'Für die weitere Bearbeitung des Antrags von Lena Hoffmann benötigen wir eine Rückmeldung bis zum 04.09.2026. Danach kann es zu Verzögerungen kommen.'}
 ],
 events:[
  {id:'e1',date:'2026-08-27',title:'Telefonat Betreuungsgericht',type:'followup',personId:'p1',source:'manual'},
  {id:'e2',date:'2026-09-01',title:'Hilfeplangespräch',type:'appointment',personId:'p2',source:'manual'}
 ]
};

let state=load();let selectedMail=null;let mailFilter='all';let calDate=new Date(today.getFullYear(),today.getMonth(),1);
function clone(v){return JSON.parse(JSON.stringify(v))}
function load(){try{return JSON.parse(localStorage.getItem(STORAGE))||clone(seed)}catch{return clone(seed)}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1900)}
function person(id){return state.people.find(p=>p.id===id)}
function extractDate(text){const matches=[...text.matchAll(/\b(\d{1,2})\.(\d{1,2})\.(\d{4})\b/g)];if(!matches.length)return null;const m=matches[matches.length-1];return iso(+m[3],+m[2],+m[1])}
function detectedType(mail){return /frist|spätestens|bis zum|benötigen.*bis/i.test(mail.body)?'deadline':(/termin|uhr/i.test(mail.body)?'appointment':null)}
function syncMailEvent(mail){const date=extractDate(mail.body),type=detectedType(mail);if(!date||!type)return;const id='mail-'+mail.id;const title=type==='deadline'?`Frist: ${mail.subject}`:`Termin: ${mail.subject}`;const existing=state.events.find(e=>e.id===id);if(existing){Object.assign(existing,{date,title,type,personId:mail.personId,source:'mail'})}else state.events.push({id,date,title,type,personId:mail.personId,source:'mail'})}
state.mails.forEach(syncMailEvent);save();

function setView(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelector(`#${view}-view`).classList.add('active');document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={dashboard:['ARBEITSBEREICH','Guten Tag'],calendar:['PLANUNG','Kalender & Fristen'],mail:['KOMMUNIKATION','E-Mail Verwaltung'],people:['FALLMANAGEMENT','Personenakten']};document.querySelector('#viewEyebrow').textContent=titles[view][0];document.querySelector('#viewTitle').textContent=titles[view][1];render()}

document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>setView(b.dataset.jump));
document.querySelector('#heroDate').textContent=new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(today);

function render(){renderStats();renderDashboard();renderCalendar();renderMail();renderPeople()}
function renderStats(){const deadlines=state.events.filter(e=>e.type==='deadline');const unassigned=state.mails.filter(m=>!m.personId).length;const notes=state.people.reduce((a,p)=>a+p.notes.length,0);document.querySelector('#statDeadlines').textContent=deadlines.length;document.querySelector('#statMails').textContent=unassigned;document.querySelector('#statPeople').textContent=state.people.length;document.querySelector('#statNotes').textContent=notes;document.querySelector('#navDeadlineBadge').textContent=deadlines.length;document.querySelector('#navMailBadge').textContent=unassigned;document.querySelector('#statDeadlinesHint').textContent=deadlines.length?'automatisch & manuell erfasst':'keine offenen Fristen'}
function sortedEvents(){return [...state.events].sort((a,b)=>a.date.localeCompare(b.date))}
function chip(date){const d=new Date(date+'T12:00:00');return `<div class="date-chip"><strong>${pad(d.getDate())}</strong><span>${new Intl.DateTimeFormat('de-DE',{month:'short'}).format(d)}</span></div>`}
function renderDashboard(){document.querySelector('#dashboardDeadlines').innerHTML=sortedEvents().filter(e=>e.type==='deadline').slice(0,5).map(e=>`${chip(e.date)}<div><div class="item-title">${esc(e.title.replace('Frist: ',''))}</div><div class="item-sub">${person(e.personId)?.name||'Noch keiner Akte zugeordnet'}</div></div><span class="badge deadline">Frist</span>`).map(x=>`<div class="deadline-row">${x}</div>`).join('')||'<div class="empty-state"><p>Keine Fristen vorhanden.</p></div>';document.querySelector('#dashboardMails').innerHTML=[...state.mails].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4).map(m=>`<div class="mini-mail"><div class="person-initials">${initials(m.from)}</div><div><div class="item-title">${esc(m.subject)}</div><div class="item-sub">${esc(m.from)} · ${fmt(m.date)}</div></div>${m.personId?'<span class="badge">zugeordnet</span>':'<span class="badge deadline">offen</span>'}</div>`).join('')}
function renderCalendar(){const y=calDate.getFullYear(),m=calDate.getMonth();document.querySelector('#monthLabel').textContent=new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(calDate);const first=new Date(y,m,1),offset=(first.getDay()+6)%7,start=new Date(y,m,1-offset);let html='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const ds=iso(d.getFullYear(),d.getMonth()+1,d.getDate()),muted=d.getMonth()!==m,isToday=ds===iso(today.getFullYear(),today.getMonth()+1,today.getDate());const events=state.events.filter(e=>e.date===ds).slice(0,3);html+=`<div class="day ${muted?'muted':''} ${isToday?'today':''}"><div class="day-number">${d.getDate()}</div>${events.map(e=>`<div class="cal-event ${e.type}" title="${esc(e.title)}">${esc(e.title.replace('Frist: ','').replace('Termin: ',''))}</div>`).join('')}</div>`}document.querySelector('#calendarGrid').innerHTML=html;document.querySelector('#agendaList').innerHTML=sortedEvents().filter(e=>e.date>=iso(today.getFullYear(),today.getMonth()+1,today.getDate())).slice(0,9).map(e=>`<div class="agenda-row">${chip(e.date)}<div><div class="item-title">${esc(e.title)}</div><div class="item-sub">${person(e.personId)?.name||'Ohne Aktenzuordnung'}</div></div><span class="badge ${e.type}">${e.type==='deadline'?'Frist':e.type==='appointment'?'Termin':'Wiedervorlage'}</span></div>`).join('')}
document.querySelector('#prevMonth').onclick=()=>{calDate=new Date(calDate.getFullYear(),calDate.getMonth()-1,1);renderCalendar()};document.querySelector('#nextMonth').onclick=()=>{calDate=new Date(calDate.getFullYear(),calDate.getMonth()+1,1);renderCalendar()};

function renderMail(){let mails=[...state.mails].sort((a,b)=>b.date.localeCompare(a.date));if(mailFilter==='unassigned')mails=mails.filter(m=>!m.personId);if(mailFilter==='deadline')mails=mails.filter(m=>detectedType(m)==='deadline');document.querySelector('#mailList').innerHTML=mails.map(m=>`<div class="mail-card ${m.unread?'unread':''} ${selectedMail===m.id?'active':''}" data-mail="${m.id}"><div class="mail-meta"><span>${esc(m.from)}</span><span>${fmt(m.date)}</span></div><div class="mail-subject">${esc(m.subject)}</div><div class="mail-preview">${esc(m.body.replace(/\n/g,' ').slice(0,115))}…</div></div>`).join('');document.querySelectorAll('[data-mail]').forEach(el=>el.onclick=()=>{selectedMail=el.dataset.mail;const m=state.mails.find(x=>x.id===selectedMail);m.unread=false;save();renderMail();renderStats();renderReader(m)});if(selectedMail){const m=state.mails.find(x=>x.id===selectedMail);if(m)renderReader(m)}}
function renderReader(m){const d=extractDate(m.body),type=detectedType(m);document.querySelector('#mailReader').innerHTML=`<span class="section-kicker">${esc(m.from)} · ${fmt(m.date)}</span><h2>${esc(m.subject)}</h2><div class="item-sub">${esc(m.sender)}</div>${d&&type?`<div class="reader-actions"><span class="badge ${type}">Automatisch erkannt: ${type==='deadline'?'Frist':'Termin'} ${fmt(d)}</span></div>`:''}<div class="message">${esc(m.body)}</div><div class="reader-actions"><select class="select-inline" id="assignSelect"><option value="">— Akte auswählen —</option>${state.people.map(p=>`<option value="${p.id}" ${m.personId===p.id?'selected':''}>${esc(p.name)} · ${esc(p.caseNumber)}</option>`).join('')}</select><button class="primary-btn" id="assignMail">In Personenakte verschieben</button>${m.personId?`<button class="secondary-btn" id="openAssigned">Akte öffnen</button>`:''}</div>`;document.querySelector('#assignMail').onclick=()=>{const id=document.querySelector('#assignSelect').value;if(!id)return toast('Bitte zuerst eine Personenakte wählen.');m.personId=id;syncMailEvent(m);save();toast('E-Mail und erkannte Frist wurden der Akte zugeordnet.');render();renderReader(m)};const open=document.querySelector('#openAssigned');if(open)open.onclick=()=>{setView('people');setTimeout(()=>{document.querySelector(`[data-person="${m.personId}"]`)?.classList.add('open')},0)}}
document.querySelectorAll('[data-mail-filter]').forEach(b=>b.onclick=()=>{mailFilter=b.dataset.mailFilter;document.querySelectorAll('[data-mail-filter]').forEach(x=>x.classList.toggle('active',x===b));renderMail()});

function renderPeople(query=''){const q=query.toLowerCase();const arr=state.people.filter(p=>`${p.name} ${p.caseNumber} ${p.category}`.toLowerCase().includes(q));document.querySelector('#peopleCount').textContent=`${arr.length} Akte${arr.length===1?'':'n'}`;document.querySelector('#peopleList').innerHTML=arr.map(p=>{const mails=state.mails.filter(m=>m.personId===p.id),events=state.events.filter(e=>e.personId===p.id);return `<article class="person-card" data-person="${p.id}"><div class="person-summary"><div class="person-initials">${initials(p.name)}</div><div><div class="person-name">${esc(p.name)}</div><div class="person-meta">${esc(p.caseNumber)} · ${esc(p.category)}</div></div><div class="person-stats"><span class="badge">${mails.length} Mails</span><span class="badge deadline">${events.filter(e=>e.type==='deadline').length} Fristen</span><span class="badge">${p.notes.length} Notizen</span></div><span>⌄</span></div><div class="person-detail"><div class="detail-grid"><section class="detail-box"><h4>E-Mails</h4>${mails.length?mails.map(m=>`<div class="mini-linked-mail"><strong>${esc(m.subject)}</strong><div class="item-sub">${esc(m.from)} · ${fmt(m.date)}</div></div>`).join(''):'<div class="item-sub">Noch keine E-Mails zugeordnet.</div>'}</section><section class="detail-box"><h4>Fristen & Termine</h4>${events.length?events.sort((a,b)=>a.date.localeCompare(b.date)).map(e=>`<div class="mini-linked-mail"><strong>${esc(e.title)}</strong><div class="item-sub">${fmt(e.date)} · ${e.type}</div></div>`).join(''):'<div class="item-sub">Keine Einträge vorhanden.</div>'}</section><section class="detail-box" style="grid-column:1/-1"><h4>Notizen</h4><div class="notes">${p.notes.length?p.notes.slice().reverse().map(n=>`<div class="note">${esc(n.text)}<div class="item-sub">${fmt(n.created)}</div></div>`).join(''):'<div class="item-sub">Noch keine Notizen.</div>'}</div><div class="note-form"><input placeholder="Neue Notiz zur Akte …" data-note-input="${p.id}"><button class="primary-btn" data-add-note="${p.id}">Speichern</button></div></section></div></div></article>`}).join('');document.querySelectorAll('.person-summary').forEach(s=>s.onclick=()=>s.parentElement.classList.toggle('open'));document.querySelectorAll('[data-add-note]').forEach(b=>b.onclick=()=>{const p=person(b.dataset.addNote),inp=document.querySelector(`[data-note-input="${p.id}"]`),text=inp.value.trim();if(!text)return;p.notes.push({id:'n'+Date.now(),text,created:iso(today.getFullYear(),today.getMonth()+1,today.getDate())});save();render();const card=document.querySelector(`[data-person="${p.id}"]`);if(card)card.classList.add('open');toast('Notiz gespeichert.')})}
document.querySelector('#peopleSearch').oninput=e=>renderPeople(e.target.value);document.querySelector('#globalSearch').onkeydown=e=>{if(e.key==='Enter'){setView('people');document.querySelector('#peopleSearch').value=e.target.value;renderPeople(e.target.value)}};

const dlg=document.querySelector('#personDialog');document.querySelector('#addPersonBtn').onclick=()=>dlg.showModal();document.querySelector('#savePerson').onclick=e=>{e.preventDefault();const fd=new FormData(document.querySelector('#personForm')),name=fd.get('name').trim(),caseNumber=fd.get('caseNumber').trim();if(!name||!caseNumber)return;state.people.push({id:'p'+Date.now(),name,caseNumber,category:fd.get('category'),notes:fd.get('note').trim()?[{id:'n'+Date.now(),text:fd.get('note').trim(),created:iso(today.getFullYear(),today.getMonth()+1,today.getDate())}]:[]});save();dlg.close();document.querySelector('#personForm').reset();render();toast('Neue Personenakte angelegt.')};
document.querySelector('#resetDemo').onclick=()=>{if(confirm('NicoPanel-Demodaten wirklich zurücksetzen?')){state=clone(seed);state.mails.forEach(syncMailEvent);save();selectedMail=null;render();toast('Demodaten zurückgesetzt.')}};
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
render();